# Offense count: 4
# Configuration parameters: AllowComments, AllowNil.
Lint/SuppressedException:
  Exclude:
    - 'lib/premailer/adapter/nokogiri.rb'
    - 'lib/premailer/adapter/nokogiri_fast.rb'
    - 'lib/premailer/adapter/nokogumbo.rb'
    - 'lib/premailer/premailer.rb'
